# SITE CONFIGURATION
baseurl: ""
url: "https://jwkang.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Krnomad's Tech note
  avatar: #assets/img/avatar.png
  favicon: #assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "docker c++ python jenkins crwaling android java c" # used by search engines - Short description, primarily used by search engines

  # Header and footer text
  header_text: >
     <p>블로그 공사 중 입니다</p>
  header_text_feature_image:
  footer_text: >
   This blog is made by <a href="https://jekyllrb-ko.github.io/">jekyll </a>

  # Icons
  rss: true
  email_address: krnomad@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: https://www.facebook.com/krnomad
  flickr:
  gitlab:
  github: "https://github.com/jwkang"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/jongwon-kang-356b14112/ # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  https://stackoverflow.com/users/8520403/frank # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-113471771-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
